export type {
  MintayAlignment,
  MintayBorder,
  MintayColor,
  MintayFill,
  MintayFontWeight,
  MintayGradient,
  MintayLayoutMode,
  MintayNode,
  MintayNodeType,
  MintayParseResult,
  MintayScreen,
  MintayShadow,
  MintayTextAlign,
} from '../../../shared/types/mintaySchema';
